### ISSUE TITLE
AssertionError: version mismatch, 0.8.6 != 1.8.3

### ISSUE THREAD

**Issue by vishalkrtr** [DanMcInerney/xsscrapy#30]
>> python get-pip.py 
Traceback (most recent call last):
  File "get-pip.py", line 19177, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpR1SH6k/pip.zip/pip/__init__.py", line 16, in <module>
  File "/tmp/tmpR1SH6k/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpR1SH6k/pip.zip/pip/download.py", line 39, in <module>
  File "/tmp/tmpR1SH6k/pip.zip/pip/_vendor/requests/__init__.py", line 53, in <module>
  File "/tmp/tmpR1SH6k/pip.zip/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 0.8.6 != 1.8.3

**Comment by binarycanary** [comment]
@vishalkrtr I was wondering if you might be able to give more context around why or when this error occurred?

`get-pip.py` is a different GitHub project located here: [https://github.com/pypa/get-pip](https://github.com/pypa/get-pip). If your error is related to `get-pip.py`, as it appears to be, you will have more luck opening an issue with that project.

One thing you might want to try before opening a ticket with that project is running the command with elevated privileges. In Windows that would mean running in an Administrator command prompt. In Linux that would mean running `sudo python get-pip.py`.

A quick google search of your error message also shows that some Linux users have had success in fixing that issue by first installing the foreign function interface components before running get-pip.py. I would also try: `sudo apt-get install python-cffi`, then `sudo python get-pip.py`

**Comment by vishalkrtr** [comment]
Thanks man my issue is resolved by installing python-cffi . Thanks a lot
^_^...
