### ISSUE TITLE
the new version does not work

### ISSUE THREAD

**Issue by lacroutelacroute** [DanMcInerney/xsscrapy#34]
after the new version and install from scratch
surprise install dependance is very difficult to install
and xssscrapy.py dont start with error

$ sudo python ./xsscrapy.py -h
Traceback (most recent call last):
  File "./xsscrapy.py", line 5, in <module>
    from xsscrapy.spiders.xss_spider import XSSspider
  File "/opt/xssscrapy/xsscrapy/xsscrapy/spiders/xss_spider.py", line 3, in <module>
    from scrapy.linkextractors import LinkExtractor
ImportError: No module named linkextractors

**Comment by lacroutelacroute** [comment]
additional output
 $ sudo pip    install  -r  requirements.txt 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Twisted in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: w3lib in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: lxml in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: cssselect in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pyopenssl in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: cryptography in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: queuelib in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: Scrapy==1.1.0rc3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 10))
Collecting pybloom==1.1 (from -r requirements.txt (line 11))
  Using cached pybloom-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z2r8o7x8/pybloom/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-z2r8o7x8/pybloom/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z2r8o7x8/pybloom/

**Comment by lacroutelacroute** [comment]
for to have a correct operation it is necessary to write pip2.7
$ sudo pip2.7 install -r requirements.txtRequirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Twisted in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: w3lib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: cssselect in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pyopenssl in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: queuelib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Collecting Scrapy==1.1.0rc3 (from -r requirements.txt (line 10))
  Using cached Scrapy-1.1.0rc3-py2.py3-none-any.whl
Collecting pybloom==1.1 (from -r requirements.txt (line 11))
  Using cached pybloom-1.1.tar.gz
Requirement already satisfied: zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 2))
Requirement already satisfied: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 8))
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 8))
Requirement already satisfied: pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 8))
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 8))
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python2.7/dist-packages/idna-2.1-py2.7.egg (from cryptography->-r requirements.txt (line 8))
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 8))
Requirement already satisfied: service-identity in /usr/local/lib/python2.7/dist-packages/service_identity-16.0.0-py2.7.egg (from Scrapy==1.1.0rc3->-r requirements.txt (line 10))
Collecting parsel>=0.9.3 (from Scrapy==1.1.0rc3->-r requirements.txt (line 10))
  Using cached parsel-1.0.3-py2.py3-none-any.whl
Requirement already satisfied: PyDispatcher>=2.0.5 in /usr/local/lib/python2.7/dist-packages (from Scrapy==1.1.0rc3->-r requirements.txt (line 10))
Requirement already satisfied: bitarray>=0.3.4 in /usr/local/lib/python2.7/dist-packages (from pybloom==1.1->-r requirements.txt (line 11))
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography->-r requirements.txt (line 8))
Requirement already satisfied: attrs in /usr/local/lib/python2.7/dist-packages/attrs-16.2.0-py2.7.egg (from service-identity->Scrapy==1.1.0rc3->-r requirements.txt (line 10))
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python2.7/dist-packages/pyasn1_modules-0.0.8-py2.7.egg (from service-identity->Scrapy==1.1.0rc3->-r requirements.txt (line 10))
Building wheels for collected packages: pybloom
  Running setup.py bdist_wheel for pybloom ... done
  Stored in directory: /root/.cache/pip/wheels/c5/36/47/a4d71b4f39d2b8a82d29ceee6b7d65b45700ec6744e63e0eb8
Successfully built pybloom
Installing collected packages: parsel, Scrapy, pybloom
  Found existing installation: Scrapy 0.24.4
    Uninstalling Scrapy-0.24.4:
      Successfully uninstalled Scrapy-0.24.4
  Found existing installation: pybloom 2.0.0
    Uninstalling pybloom-2.0.0:
      Successfully uninstalled pybloom-2.0.0
Successfully installed Scrapy-1.1.0rc3 parsel-1.0.3 pybloom-1.1
fakessh@fakessh:/opt/xssscrapy/xsscrapy$ sudo python ./xsscrapy.py -h
usage: xsscrapy.py [-h] [-u URL] [-l LOGIN] [-p PASSWORD] [-c CONNECTIONS]
                   [-r RATELIMIT] [--basic] [-k COOKIE]

optional arguments:
  -h, --help            show this help message and exit
  -u URL, --url URL     URL to scan; -u http://example.com
  -l LOGIN, --login LOGIN
                        Login name; -l danmcinerney
  -p PASSWORD, --password PASSWORD
                        Password; -p pa$$w0rd
  -c CONNECTIONS, --connections CONNECTIONS
                        Set the max number of simultaneous connections
                        allowed, default=30
  -r RATELIMIT, --ratelimit RATELIMIT
                        Rate in requests per minute, default=0
  --basic               Use HTTP Basic Auth to login
  -k COOKIE, --cookie COOKIE
                        Cookie key; --cookie
                        SessionID=afgh3193e9103bca9318031bcdf
