### ISSUE TITLE
Urlparse Module not found 

### ISSUE THREAD

**Issue by Sydwicked** [DanMcInerney/xsscrapy#44]

**Comment by iNoSec** [comment]
do you find a solution?? thx

**Comment by decidedlygray** [comment]
What version of python are you using?

**Comment by Codeskin-byte** [comment]
@Sydwicked , I also had the same issue. This error has occured with python 3.x environment and xssscrapy module is supported only with python 2.x. So to fix it you have to change in file xsscrapy/xss_spider.py line 9, 
change
from urlparse import urlparse, parse_qsl, urljoin, urlunparse, urlunsplit
to
import urllib.parse as urlparse
from urllib.parse import parse_qsl, urljoin, urlunparse, urlunsplit.

Hope it helps!

**Comment by shivam530** [comment]
Traceback (most recent call last):
  File "/home/kali/Desktop/xsscrapy/xsscrapy.py", line 5, in <module>
    from xsscrapy.spiders.xss_spider import XSSspider
  File "/home/kali/Desktop/xsscrapy/xsscrapy/spiders/xss_spider.py", line 9, in <module>
    from urlparse import urlparse, parse_qsl, urljoin, urlunparse, urlunsplit
ModuleNotFoundError: No module named 'urlparse'
