### ISSUE TITLE
Xsscrapy pybloom installing error

### ISSUE THREAD

**Issue by ImPRINCE99** [DanMcInerney/xsscrapy#53]
Hello,
I am not able to use xsscrapy in Kali Linux 2019.3 version.
I had also checked older verison but the same error is coming.

/xsscrapy# pip install -r requirements.txt
Collecting Scrapy==1.1.0rc3
  Using cached Scrapy-1.1.0rc3-py2.py3-none-any.whl (292 kB)
Collecting pybloom==1.1
  Using cached pybloom-1.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_k89_9hy/pybloom/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_k89_9hy/pybloom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_k89_9hy/pybloom/pip-egg-info
         cwd: /tmp/pip-install-_k89_9hy/pybloom/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_k89_9hy/pybloom/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-install-_k89_9hy/pybloom/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by decidedlygray** [comment]
If I recall correctly, xsscrapy is currently Python 2. Based on your error message it looks like you’re attempting to use Python 3
