### ISSUE TITLE
Facing this issue while installing requirements.txt

### ISSUE THREAD

**Issue by h4ck3rone** [DanMcInerney/xsscrapy#60]
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jzd70atp/pybloom_18079700ea8147b8921576e7f2418b13/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jzd70atp/pybloom_18079700ea8147b8921576e7f2418b13/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4mh1s55h
         cwd: /tmp/pip-install-jzd70atp/pybloom_18079700ea8147b8921576e7f2418b13/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jzd70atp/pybloom_18079700ea8147b8921576e7f2418b13/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-install-jzd70atp/pybloom_18079700ea8147b8921576e7f2418b13/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1a/82/a1ad015bdc19bd7e10aa97070329b84b5e01c0c6b5de88df664a98413eed/pybloom-1.1.tar.gz#sha256=f90903f2229135833a3ce115709662a4f4ea49bdfffc7d62a3061bd9021ac485 (from https://pypi.org/simple/pybloom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pybloom==1.1
ERROR: No matching distribution found for pybloom==1.1

**Comment by Mentsh** [comment]
Here is your issue."/usr/local/bin/**python3.9**" XSScrapy is written with **2.7 python** - install that version ( hint 2.7 and 3.* can live on the same system.)
Then run it with 2.7

**Comment by decidedlygray** [comment]
@spider8892 please try the instructions I posted here - https://github.com/DanMcInerney/xsscrapy/issues/42#issuecomment-770297523

**Comment by spider8892** [comment]
> @spider8892 please try the instructions I posted here - [#42 (comment)](https://github.com/DanMcInerney/xsscrapy/issues/42#issuecomment-770297523)

Step 3 - Change our python to point to python2 
is not working on my terminal

pyenv install 2.7.18
Command 'pyenv' not found, did you mean:
  command 'p7env' from deb libnss3-tools
Try: apt install <deb name>

**Comment by decidedlygray** [comment]
Something was missed with Step 1 - did you get any errors when installing pyenv? Please re-run the steps in Step 1. Also be sure to close your terminal and open a new one

**Comment by ImPRINCE99** [comment]
Please solve this last error 

![image](https://user-images.githubusercontent.com/60551509/109107333-86a8c680-7757-11eb-81e6-971b330536aa.png)

**Comment by mmandlesara** [comment]
please solve this error.
/usr/share/offsec-awae-wheels/pyOpenSSL-19.1.0-py2.py3-none-any.whl/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
2021-06-30 03:14:39 [scrapy.utils.log] INFO: Scrapy 1.8.0 started (bot: xsscrapy)
2021-06-30 03:14:39 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 16.6.0, Python 2.7.18 (default, Apr 28 2021, 17:39:59) - [GCC 10.2.1 20210110], pyOpenSSL 19.1.0 (OpenSSL 1.1.1i  8 Dec 2020), cryptography 3.3.2, Platform Linux-5.9.0-kali1-amd64-x86_64-with-debian-kali-rolling
2021-06-30 03:14:39 [scrapy.crawler] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'xsscrapy.spiders', 'DUPEFILTER_CLASS': 'xsscrapy.bloomfilters.BloomURLDupeFilter', 'SPIDER_MODULES': ['xsscrapy.spiders'], 'CONCURRENT_REQUESTS': '30', 'BOT_NAME': 'xsscrapy', 'DOWNLOAD_DELAY': '0'}
2021-06-30 03:14:39 [scrapy.extensions.telnet] INFO: Telnet Password: 7c274c008e63de61
2021-06-30 03:14:39 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
Unhandled error in Deferred:
2021-06-30 03:14:39 [twisted] CRITICAL: Unhandled error in Deferred:

2021-06-30 03:14:39 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 104, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scheduler_cls = load_object(self.settings['SCHEDULER'])
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 46, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/scheduler.py", line 7, in <module>
    from queuelib import PriorityQueue
  File "/usr/local/lib/python2.7/dist-packages/queuelib/__init__.py", line 1, in <module>
    from queuelib.queue import FifoDiskQueue, LifoDiskQueue
  File "/usr/local/lib/python2.7/dist-packages/queuelib/queue.py", line 7, in <module>
    from contextlib import suppress
ImportError: cannot import name suppress

**Comment by ImPRINCE99** [comment]
The modules are removes by the pip
So, from now onwords we can't use xsscrapy.

Same issue was faced by me

**Comment by mmandlesara** [comment]
thank you bro

**Comment by mmandlesara** [comment]
@ImPRINCE99 can u please share what do u tool used right now ?

**Comment by ImPRINCE99** [comment]
See I  suggest you to do Manual hunting.
By hunting Manually I am getting 20 XSS per day.
And when I was using scrapy It was like 5 XSS per day

**Comment by mmandlesara** [comment]
@ImPRINCE99  is it a tool of kali (scrapy)?

**Comment by ImPRINCE99** [comment]
I mean Xsscrapy
