### ISSUE TITLE
Error of  execution

### ISSUE THREAD

**Issue by tXambe** [DanMcInerney/xsscrapy#68]
Hello,

When I run this script I have this error:

```
Traceback (most recent call last):
  File "/opt/XSS/xsscrapy/xsscrapy.py", line 4, in <module>
    from scrapy.cmdline import execute
ModuleNotFoundError: No module named 'scrapy'

```

My version of python -->  Python 3.9.7
My OS --> Linux 5.14.0-kali2-amd64 #1 SMP Debian 5.14.9-2kali1 (2021-10-04) x86_64 GNU/Linux

A greeting and thanks

**Comment by Mentsh** [comment]
Look at the requirements. This script is written in Python 2.*  therefore it needs Python 2.*

You are using Python 3.* - objects are written different between the two.. so not compatible

**Comment by tXambe** [comment]
Hello,

sorry I did not see the requirements. My version is Python 2.7.18

sudo python2 xsscrapy.py -u http://altoromutual.com                                                 
Traceback (most recent call last):
  File "xsscrapy.py", line 4, in <module>
    from scrapy.cmdline import execute
ImportError: No module named scrapy.cmdline


A greeting and thanks
