### ISSUE TITLE
Twisted Error when i run any URL

### ISSUE THREAD

**Issue by hackermanxyz** [DanMcInerney/xsscrapy#69]
when i run any URL like " python xsscrapy.py -u https://example.com "
so i got this error.

2022-02-09 22:19:55 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
Unhandled error in Deferred:
2022-02-09 22:19:55 [twisted] CRITICAL: Unhandled error in Deferred:

2022-02-09 22:19:55 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 72, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 97, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 66, in __init__
    self.scheduler_cls = load_object(self.settings['SCHEDULER'])
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/scheduler.py", line 6, in <module>
    from queuelib import PriorityQueue
  File "/usr/local/lib/python2.7/dist-packages/queuelib/__init__.py", line 1, in <module>
    from queuelib.queue import FifoDiskQueue, LifoDiskQueue
  File "/usr/local/lib/python2.7/dist-packages/queuelib/queue.py", line 7, in <module>
    from contextlib import suppress
ImportError: cannot import name suppress

please help me and fix this issue 
thank you.
![XSScrapy error](https://user-images.githubusercontent.com/70416142/153331336-d5ff705f-8bea-4eba-967c-8dcc64f60146.png)

**Comment by decidedlygray** [comment]
No promises, but downgrading queuelib may fix the issue:

```
pip uninstall attrs
pip uninstall queuelib
pip install queuelib==1.5.0
pip install attrs

```

It looks like modern versions of some of those libraries require python3. If that doesn't work I might be able to find my working version and get a version locked requirements.txt for you
