### ISSUE TITLE
Error while proceeding python xsscrapy.py

### ISSUE THREAD

**Issue by Noobsayed** [DanMcInerney/xsscrapy#79]
Traceback (most recent call last):
  File "/home/kali/Tools/xsscrapy/xsscrapy.py", line 4, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python3.11/dist-packages/scrapy/__init__.py", line 15, in <module>
    from scrapy.spiders import Spider
  File "/usr/local/lib/python3.11/dist-packages/scrapy/spiders/__init__.py", line 106, in <module>
    from scrapy.spiders.crawl import CrawlSpider, Rule
  File "/usr/local/lib/python3.11/dist-packages/scrapy/spiders/crawl.py", line 15, in <module>
    from scrapy.utils.spider import iterate_spider_output
  File "/usr/local/lib/python3.11/dist-packages/scrapy/utils/spider.py", line 24, in <module>
    from scrapy.utils.defer import deferred_from_coro
  File "/usr/local/lib/python3.11/dist-packages/scrapy/utils/defer.py", line 37, in <module>
    from scrapy.utils.reactor import _get_asyncio_event_loop, is_asyncio_reactor_installed
  File "/usr/local/lib/python3.11/dist-packages/scrapy/utils/reactor.py", line 8, in <module>
    from twisted.internet import asyncioreactor, error
  File "/usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py", line 19, in <module>
    from twisted.internet.posixbase import (
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 38, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import (
  File "/usr/local/lib/python3.11/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.11/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by Mentsh** [comment]
This is still a Python 2 application.

You appear to be using Python 3

**Comment by Noobsayed** [comment]
python3 xsscrapy.py
Traceback (most recent call last):
  File "/home/kali/Tools/xsscrapy/xsscrapy.py", line 4, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python3.11/dist-packages/scrapy/__init__.py", line 15, in <module>
    from scrapy.spiders import Spider
  File "/usr/local/lib/python3.11/dist-packages/scrapy/spiders/__init__.py", line 106, in <module>
    from scrapy.spiders.crawl import CrawlSpider, Rule
  File "/usr/local/lib/python3.11/dist-packages/scrapy/spiders/crawl.py", line 15, in <module>
    from scrapy.utils.spider import iterate_spider_output
  File "/usr/local/lib/python3.11/dist-packages/scrapy/utils/spider.py", line 24, in <module>
    from scrapy.utils.defer import deferred_from_coro
  File "/usr/local/lib/python3.11/dist-packages/scrapy/utils/defer.py", line 37, in <module>
    from scrapy.utils.reactor import _get_asyncio_event_loop, is_asyncio_reactor_installed
  File "/usr/local/lib/python3.11/dist-packages/scrapy/utils/reactor.py", line 8, in <module>
    from twisted.internet import asyncioreactor, error
  File "/usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py", line 19, in <module>
    from twisted.internet.posixbase import (
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 38, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import (
  File "/usr/local/lib/python3.11/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.11/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

same error after using python3 xsscrapy.py

**Comment by Noobsayed** [comment]
python2 xsscrapy.py
Traceback (most recent call last):
  File "xsscrapy.py", line 4, in <module>
    from scrapy.cmdline import execute
ImportError: No module named scrapy.cmdline


error while using command:  python2 xsscrapy.py

**Comment by decidedlygray** [comment]
Did you get any errors when running the install commands?

```

wget -O -u https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install -r requirements.txt

```

**Comment by Noobsayed** [comment]
python get-pip.py                                     
python: can't open file '/home/kali/Tools/get-pip.py': [Errno 2] No such file or directory

**Comment by decidedlygray** [comment]
Can you post the full output, including executing wget?
